config/routes.rb
Rails.application.routes.draw do

  resources :users
  get '/signup' => 'users#new'

  resources :photos

  resources :events do 
    post 'attend', on: :member
    delete 'leave', on: :member
  end

  resources :posts do 
    post 'postingevent', on: :member
  end

  resources :friendships

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'users#index'

end

app/models/user.rb
#require 'carrierwave/orm/activerecord'

class User < ActiveRecord::Base
	has_many :events_attending, through: :users_events, class_name: Event, source: :event, dependent: :destroy  #events users are attending
	has_many :users_events, dependent: :destroy
	has_many :created_events, class_name: Event, foreign_key: "creator_id", dependent: :destroy
	has_many :posts, foreign_key: "user_id", dependent: :destroy
	has_many :requestor, through: :event_requests
	has_many :receiving, through: :event_requests

    has_many :friendships
    has_many :passive_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
    #passive_friendshhip is other user requesting

    has_many :active_friends, -> { where(friendships: { approved: true}) }, :through => :friendships, :source => :friend
    has_many :passive_friends, -> { where(friendships: { approved: true}) }, :through => :passive_friendships, :source => :user
    has_many :pending_friends, -> { where(friendships: { approved: false}) }, :through => :friendships, :source => :friend
    has_many :requested_friendships, -> { where(friendships: { approved: false}) }, :through => :passive_friendships, :source => :user
	#mount_uploader :image, AvatarUploader
	mount_uploader :image, AvatarUploader
    has_many :photos


    def friends
      active_friends | passive_friends
    end


	has_secure_password

	# attr_reader :password

	validates :name, presence: true
    validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
    validates :password, presence: true, confirmation: true, length: { in: 6..20 }

      # def password=(unencrypted_password)
      #   unless unencrypted_password.empty?
      #     @password = unencrypted_password
      #     self.password_digest = BCrypt::Password.create(unencrypted_password)
      #   end
      # end
      
	# def created_events
	# 	Event.where(creator: self)
	# 	#u.created_events.  return an array of all events.
	# 	#self refers to the user that's calling the method.
	# 	#instance method a method thats called by an instance of the class.
	# 	#a speciifc user is calling the method.
	# end



	# def events
	# 	@events_arr = [] #empty array
	# 	@user = User.where(id: self.id) #find the user
	# 	events = @user[0].users_events #find the event for the user throug the join table
	# 	users_events.each do |u| #looping through join table event for the user
	# 		@events_arr.push(u) #pushing each events into the array
	# 	end
	# 	@events_arr #returning array
	# end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authorize?, only: :edit 


  def index
    @users = User.all

  end

  def show
    @user = User.find(params[:id])
    @user_attending = @user.events_attending
    @user_posting = @user.posts
    @requests = Friendship.where(user_id: @user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      #this creates a session with the user that just signed up
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      #render "Edit" 
      render :edit
    end
  end

  def destroy
    # @user = User.find(params[:id])
    # @user.destroy
    # redirect_to users_path
    @user = User.find(params[:id])
    if(params[:id] == session[:user_id])
      session.delete(:user_id)
    end
    @user.destroy
    redirect_to users_path
  end

private
  
  def user_params
    params.require(:user).permit(:name, :email, :address, :city, :state, :zip, :password, :password_confirmation, :image)
  end

  def authorize?
    user = User.find(params[:id])
    if current_user != user
      redirect_to users_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit Profile Page <%= @user.name %></h1>

<!-- <form class="panel"> -->
	<%= form_for @user do |u| %>
		<div class="form-group">
			<%= u.label:name %><br>
			<%= u.text_field :name %>
		</div>

		<div class="form-group">
			<%= u.label :address %><br>
			<%= u.text_field :address %>
		</div>

		<div class="form-group">
			<%= u.label "City", :city %>
			<%= u.text_field :city %>
		</div>

		<div class="form-group">
			<%= u.label "State", :state %>
			<%= u.text_field :state %>
		</div>

		<div class="form-group">
			<%= u.label "Zip", :zip %>
			<%= u.text_field :zip %>
		</div>

		<div class="form-group">
			<%= u.label "Email", :email %>
			<%= u.text_field :email %>
		</div>

		<div class="form-group">
			<%= u.label "Password", :password %>
			<%= u.password_field :password %>
		</div>

		<div class="form-group">
			<%= u.label "Password", :password_confirmation %>
			<%= u.password_field :password_confirmation %>
		</div>

		<div class="form-group">
			<%= u.label :image, "Upload image" %>
			<%#= u.file_field :image, multiple: true %>
			<%= u.file_field :image %>
		</div>

		<div class="form-group">
			<%= u.submit "Submit" %>
		</div>
	<% end %>
<!-- </form> -->

<%#= link_to "Home Page", users_path %><br>
<%= link_to "Delete", :user, method: :delete, data: {confirm: "Are you sure?"} %>

app/views/users/index.html.erb
<h1>Welcome to Big10</h1>

<h2>Meet other outdoor enthusiasts!  Join events!</h2>

<% @users.each do |u| %>
	<ul>
		<li>
			<%= image_tag u.image.url(:thumb) %>
			<%#= image_tag u.image.url %>
			<%#= link_to image_tag u.image.url, user_path(u) %>
			<%= link_to u.name, user_path(u) %>
			<%= u.city %>
		</li>
	</ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>

<%= form_for @user do |u| %>
	<div>
		<%= u.label :name, "Name" %>
		<%= u.text_field :name %>
	</div>	

	<div>
		<%= u.label :email, "email" %>
		<%= u.text_field :email %>
	</div>
	
	<div>
		<%= u.label :address, "address" %>
		<%= u.text_field :address %>
	</div>
	
	<div>
		<%= u.label :city, "city" %>
		<%= u.text_field :city %>
	</div>
	
	<div>
		<%= u.label :state, "state" %>
		<%= u.text_field :state %>
	</div>
	
	<div>
		<%= u.label :zip, "zip" %>
		<%= u.text_field :zip %>
	</div>
	
	<div>
		<%= u.label :password, "password" %>
		<%= u.password_field :password %>
	</div>

	<div>
		<%= u.label :password_confirmation, "password confirmation" %>
		<%= u.password_field :password_confirmation %>
	</div>
		<div>
		<%= u.label :image, "Upload image" %>
		<%= u.file_field :image %>
		</div>
		
		<%= u.submit "Submit" %>

<% end %>



<%#= link_to "Home Page", users_path %>

app/views/users/show.html.erb
<%= image_tag(@user.image_url(:full)) %>

<h2><%= @user.name %>'s profile page</h2>
<%= @user.address %><br>
<%= @user.city %><br>
<%= @user.state %><br>
<%= @user.zip %><br>
<%= @user.email %><br>

<div>
      <% unless current_user == @user %>
        <%= link_to "Add Friend", friendships_path(:friend_id => @user), :method => :post %>
    <% end %>


    <h4>Friends</h4>
    <ul>
        <% @user.friends.each do |friend| %>
        <li>
          <%= friend.name %>
          <% if current_user == @user %>
            <%= link_to "Remove", friendship_path(:id => friend), :method => :delete %>
          <% end %>
        </li>
      <% end %>
    </ul>

    <% if current_user == @user %>
        <h4>Friend Requests</h4>
          <%#= @requests.inspect %>
        <ul>
            <% @user.requested_friendships.each do |request| %>
            <li>
              
              <%= link_to "Accept", friendship_path(:id => request), :method => "put" %> 
              <%= link_to "Decline", friendship_path(:id => request), :method => :delete %>
            </li>
          <% end %>
        </ul>
    <% end %>
</div>
<!-- <button>Request Friendship</button> -->
<h3>Events <%= @user.name %> Created</h3>
<ol>
<% @user.created_events.each do |e| %>
<li>
	<%#= link_to e.name, event_path(e.event_id) %><br>
	<%= link_to e.name, event_path(e) %><br>
	<%= e.description %><br>
	<%= e.address %><br>
	<%= e.city %><br>
	<%= e.state %><br>
	<%= e.zip %><br>
	<%= e.cost %><br><br>
</li>
<% end %>
</ol>

<h3>Events <%= @user.name %> attending</h3>
<ol>
<% @user.events_attending.each do |f| %> 
<li>
	<%= link_to f.name, event_path(f) %><br>
	<%= f.description %><br>
	<%= f.address %><br>
	<%= f.city %><br>
	<%= f.state %><br>
	<%= f.zip %><br>  
	<%= f.cost %><br><br>
</li>
	<% end %>
</ol>

<h3><%= @user.name %>'s Posting</h3>
<ul>
	<% @user_posting.each do |up| %>
	<li>
		<%= link_to up.title, post_path(up) %>
	</li>
	<% end %>
</ul>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>