config/routes.rb
Rails.application.routes.draw do

  resources :users
  get '/signup' => 'users#new'

  resources :photos

  resources :events do 
    post 'attend', on: :member
    delete 'leave', on: :member
  end

  resources :posts do 
    post 'postingevent', on: :member
  end

  resources :friendships

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'users#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  	
	has_many :users, through: :users_events
	has_many :users_events
	# belongs_to :creator, class_name: "User", foreign_key: "creator_id"
	belongs_to :creator, class_name: "User"
	has_many :posts, dependent: :destroy
	has_many :event_requests

	mount_uploader :image, AvatarUploader
	has_many :photos

  # 	validate :happened_at_is_valid_datetime

 	# def happened_at_is_valid_datetime
  #   	errors.add(:happened_at, 'must be a valid datetime') if ((DateTime.parse(happened_at) rescue ArgumentError) == ArgumentError)
 	# end

 	validates_date :start_date, :on_or_before => lambda { :end_date }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    #@users = User.all
    @events = Event.all
  end

  def show
    #@user = User.where(:user => user_id).first
    @event = Event.find(params[:id])
    @user_attending = @event.users.include?(current_user)
    #gets an array of users attending an event and it test to see if our current_user is one of them
    #@post = Post.find(params[:id])
    #binding.pry
    @post = Post.new 
    @posting = @event.posts
  end


  def new
    #@user = User.find(params[:id])
    @event = Event.new
  end

  def create
    #@users = User.find(params[:user_id])
    @event = Event.new(event_params)
    #@event.users << current_user #link the user(attendee) to the users_event table
    @event.creator = current_user #link the creator(user) to the event table
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end


  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      redirect_to event_path
    else
      #render 'edit'
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def attend
    # @event = Event.find(params[:id])
    # @event.users.push(current_user)
    # @event.save
    # redirect_to event_path
    @new_attendee = UsersEvent.new 
    @new_attendee.user_id = current_user.id 
    @new_attendee.event_id = params[:id]
    @new_attendee.save
    redirect_to event_path
  end

  def leave
    @event = UsersEvent.where({
      event_id: params[:id],
      user_id: current_user.id
      })
    @event.destroy_all
    redirect_to event_path
  end

  def is_Public?
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_date, :end_date, :cost, :address, :city, :state, :zip, :attendees, :is_public, :image)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_eventform.html.erb
<h1>Event Form</h1>

<div class="panel-body">

<%= form_for @event do |e| %>

	<div class="field form-group">
		<%#= e.label :name, class: "form-text-header" %>
		<%#= e.text_field :name, autofocus: true, class: "form-control"  %>
	</div>

	<div>
		<%#= e.label "Description", :description %>
		<%#= e.text_field :description %>
	</div>

	<div>
		<%#= e.label "Start Date", :start_date %>
		<%#= e.date_field :start_date %>
	</div>	

	<div>
		<%#= e.label "End Date", :end_date %>
		<%#= e.date_field :end_date %>
	</div>

	<div>
		<%#= e.label "Cost", :cost %>
		<%#= e.text_field :cost %>
	</div>
	
	<div>
		<%#= e.label "Address", :address %>
		<%#= e.text_field :address %>
	</div>

	<div>
		<%#= e.label "City", :city %>
		<%#= e.text_field :city %>
	</div>

	<div>
		<%#= e.label "State", :state %>
		<%#= e.text_field :state %>
	</div>

	<div>
		<%#= e.label "Zip", :zip %>
		<%#= e.text_field :zip %>
	</div>

	<div class="field">
	    <%#= e.label "Private?" %> <br />
	    <%#= e.check_box :is_public %> <br />
	</div>

	<div>
		<%#= e.label :image, "Upload image" %>
		<%#= e.file_field :image, multiple: true %>
		<%#= e.file_field :image %>
	</div>

		<%#= e.submit "Submit" %>
<%# end %>

<br>
<br>
<br>
<br>
<br>

	<div>
		<%= e.label "Name", :name %>
		<%= e.text_field :name %>
	</div>
	
	<div>
		<%= e.label "Description", :description %>
		<%= e.text_field :description %>
	</div>

	<div>
		<%= e.label "Start Date", :start_date %>
		<%= e.date_field :start_date %>
	</div>	

	<div>
		<%= e.label "End Date", :end_date %>
		<%= e.date_field :end_date %>
	</div>

	<div>
		<%= e.label "Cost", :cost %>
		<%= e.text_field :cost %>
	</div>
	
	<div>
		<%= e.label "Address", :address %>
		<%= e.text_field :address %>
	</div>

	<div>
		<%= e.label "City", :city %>
		<%= e.text_field :city %>
	</div>

	<div>
		<%= e.label "State", :state %>
		<%= e.text_field :state %>
	</div>

	<div>
		<%= e.label "Zip", :zip %>
		<%= e.text_field :zip %>
	</div>

		<div class="field">
		    <%= e.label "Private?" %> <br />
		    <%= e.check_box :is_public %> <br />
		</div>

		<div>
			<%= e.label :image, "Upload image" %>
			<%= e.file_field :image %>
		</div>

		<%= e.submit "Submit" %>
<% end %>

<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

</div>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit Events</h1>
<%= render 'eventform' %>


<%= link_to "Delete Event", :event, method: :delete, data: { confirm: "Are you sure?"} %>

app/views/events/index.html.erb
<h1>Here's all event</h1>
<% @events.each do |e| %>
	<ul>
		<li>
			<%= image_tag e.image.url %>
			<%= link_to e.name, event_path(e) %>
			<%= e.description %>
		</li>
	</ul>
<% end %>

app/views/events/new.html.erb
<h1>Create New Event</h1>
<%= render 'eventform' %>

<%= link_to "Event Index", events_path %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<%= image_tag(@event.image_url(:full)) %>

<ul>
	<li>
		<%= @event.name %><br>
		<%= @event.description %><br>
		<%= @event.address %><br>
		<%= @event.city %><br>
		<%= @event.state %><br>
		<%= @event.zip %><br>
		<%= @event.cost %><br>
		<%= @event.attendees %><br>
		<%= @event.start_date %><br>
		<%= @event.end_date %><br>
	</li>
</ul>

<% @event.id do |e| %>
<%= image_tag u.image.url %>
<% end %>


<br>

<% if current_user == @event.creator %>
<%= link_to "Edit Event", edit_event_path %><br>
<% end %>

<% if logged_in? %>
<% unless @user_attending %>
<%= link_to "Join Event", attend_event_path(@event), method: :post %>
<% end %>	
<% end %>

<% if @user_attending %>
<%= link_to "Leave Event", leave_event_path(@event), method: :delete %>
<% end %>

<h4>List of Attendees</h4>
<ul>
	<% @event.users.each do |f| %>
		<li>
			<%= f.name %>
		</li>
	<% end %>
</ul>



<div>
<%= form_for @post do |p| %>

	<div>
		<%= p.label "Title", :title %>
		<%= p.text_field :title %>
	</div>
	<br>
	<div>
		<%= p.label "Body", :body %>
		<%= p.text_area :body %>
	</div>

	<%= hidden_field_tag :event_id, @event.id %>

	
		<%= p.submit "Submit" %>
<% end %>
</div>


<div>
	<% @posting.each do |p| %>
	<li>
		<%= link_to p.title, post_path(p) %>
		 <%#= p.body %><br>
	</li>
	<% end %>
</div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>