config/routes.rb
Rails.application.routes.draw do

  resources :users
  get '/signup' => 'users#new'

  resources :photos

  resources :events do 
    post 'attend', on: :member
    delete 'leave', on: :member
  end

  resources :posts do 
    post 'postingevent', on: :member
  end

  resources :friendships

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'users#index'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	&copy; Trekr - Plan your trip with us not with the other guys.<br>
	
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">

	<ul id="nav-links" class="nav navbar-nav">
		<li id="nav-title"><%= link_to "BIG10", users_path %></li>
		<li><%= link_to "Events Page", events_path %></li>
		<li><%= link_to "Posts Page", posts_path %></li>

		
			<% if current_user %>
				<li><%= link_to "Create Events", new_event_path %></li>
				<li><%= link_to "Create Posts", new_post_path %></li>
			<% end %>	

			<% if logged_in? %>
			<li class="dropdown" id="dropdown-right">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Welcome: <%= current_user.name %><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  
					<li><%= link_to "Log Out", logout_path, method: :delete %></li>
					<li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
		    <% else %>
					<li><%= link_to 'Log In', login_path %></li>
					<li><%= link_to "Sign Up", signup_path %></li>
				<% end %>
                </ul>
          </li>
       
          
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Big10</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<div class="container">
	<div class="jumbotron">
		<%= yield %>
	</div>
</div>

<%= render 'layouts/footer' %>
</body>
</html>